language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - travis_retry composer self-update
    - travis_retry composer require satooshi/php-coveralls:1.0.0
    - travis_retry composer install --no-interaction --prefer-source
    - composer dump-autoload -o
    - cp tests/acceptance.conf.php.default tests/acceptance.conf.php
    - cp tests/smoke.conf.php.default tests/smoke.conf.php
    - gem install mime-types --version "< 3"
    - gem install --conservative mailcatcher > /dev/null 2>&1
    - mailcatcher --smtp-port 4456

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    - php vendor/bin/coveralls -v
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    - bash <(curl -s https://codecov.io/bash)

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
    allow_failures:
        - php: 7.0
        - php: hhvm
    fast_finish: true
